# Generated by Django 3.2.16 on 2022-12-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20220609_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gender',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='companies',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='phone_number',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='programme',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='completion_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_year',
        ),
        migrations.AddField(
            model_name='student',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
